### ISSUE TITLE
Decide on a more interesting name

### ISSUE THREAD

**Issue by SquareMan** [SquareMan/bfbb_modloader#1]
BfBB Modloader is bland and boring, we can do better!

I currently enjoy the idea of going with a robot theme that relates the Robots/Duplicatrons/etc. in the game.

DuplicatoMod 3000 *almost* fits this requirement, but it's a bit off.

D.O. Mod Loader is a clever reference to the "Don't Obey" switch in Chum Bucket Lab.

Robot names for reference: 

- duplicatotron
- fodder 
- chomp-bot
- bzzt 
- bomb-bot
- ham-mer
- g-love
- monsoon 
- chuck
- slick 
- sleepy-time 
- tubelet 
- arf
- arf dawg
- tartar

**Comment by joeyballentine** [comment]
Chum Bucket Lab

**Comment by SquilliamBFBB** [comment]
That's what I was gonna say, we already have Industrial Park, why not make this Chum Bucket Lab?

**Comment by SquareMan** [comment]
I've decided to move ahead with calling it Chum Bucket Lab.
